services:
  iperf3-webui:
    build:
      context: .
      dockerfile: Dockerfile
    #image: ghcr.io/r0gger/iperf3-webui
    container_name: iperf3-webui
    restart: unless-stopped
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    volumes:
      - ./env.yaml:/app/env.yaml
    environment:
      - PORT=${PORT:-5000}
